---
title: " "
output: 
  html_document:
    includes:
       in_header: GA_Script.html
---
A collection of oddities I stumbled across in my wanderings

# AKI

[Acute Kidney Injury as a Leading Cause of Papal Deaths in the Years 1277 to 2005: A Review of 21 Cases](http://www.ectrx.org/detail/supplement/2023/21/6/2/87/0)

-   26.9% of Popes died of AKI, 95% of which were sepsis. Mean age 69.4 +- 2.26. 28.6% stroked out.
-   John XXI in 1277 died of crush syndrome
-   Lots of gout, stones and urosepsis.

[Acute Kidney Injury Following Star Fruit Ingestion: A Case Series](10.1016/j.wem.2020.11.003)

-   Full of oxalate, crystals in urine. 
-   Calcium oxalate birefringent under polarised light on the biopsies
-   50% RRT for 1 week

# Electrolytes

[Death by coconut ](https://pubmed.ncbi.nlm.nih.gov/24550410/)

-   Did not actually die. K hit 7.8, (AKI helped).
-   Coconut water: Delicious but hypotonic, acidic, 230ml/1 cup = 600mg potassium= 2 slow K tablet ( a slow K has 600mg KCL so ~ 315mg K+ ion).

# Space

[Cosmic Kidney Disease](https://www.nature.com/articles/s41467-024-49212-1)

-   Spaceflight causes nephrolithiasis: hypercalciuria, decreased phosphorylation of NKCC2  (thus Mg, calcium wasting)
-   increased urinary oxalate - ?gut microbiome, liver production?
-   Astronauts have reduced diuresis and natriuresis.
-   SLCO2A1 downreg -( prostgladin transporter)- less reabsorption by CD PC = build up of PgE2 = increase AQP2
-   TMA and endothelial dysfunction on bx
-   loss of arterial elasticity = increased pressure wave transmission = barotrauma. + drop in BP in astronauts = CKD. 
-   Catch 22: Dilate afferent arteriole to increase flow and receive more barotrauma, on constrict to protect but generate hypoxia 

   
