---
title: " "
output: html_document
---

# IGG4 Related Disease

Almost any organ can be involved

-   Abnormal imaging in about 55% of bx positive
-   USS has renal findings in 64% of cases, enlargement or perinephric standing
-   renal mass or abnormal imaging
-   80% of patients have extra renal organs involvement
    -   38% have 1 additional organ
    -   22% have 2 additional organs
    -   19% have 3 additional organs
-   Classical: submandibular glad, lymph nodes, orbit, pancreas, retroperitoneal fibrosis, lung, parotid, kidney, aorta , bile duct.

## Clinical features

-   9% proteinuria
-   67% have elevated IgG4
-   50% have hypocomplementemia
-   30% eosinophilia
-   ANA 30%

## Renal Biopsy

TIN picture

60% of biopsy’s have AKI or CKD

-   dense lymphoplasmocytic infiltrate
-   storiform fibrosis
-   Plasma cell rich interstitial infiltrates
-   Eosinophils common
-   Expansile interstitial fibrosis, storiform
-   Increased igG4 plasma cells = \> 10 cells/field TBM deposits
-   70-80% have IgG4 BTM deposits: IgG/ K/L , C3, C1a
-   This is odd in other types of TIN

Glomerular disease phenotypes exist: MN, IGAN, MCD, MPGN

-   \~7% of IgG4 TIN have coexisting MN. Proteinuria: common, heavy (mean 8g). neg for MN abx

Note primary membranous is also igG4 dominant

## Treatment

-   90% response to steroids first line, ritux is alternative. Takes 2-4 weeks of steroids typically.
-   High relapse rate (risk factors : high serum igG4, serum igE, circulating eosinophils)
-   70% relapse post ritux
-   Watch carefully, most common gland for recurrance is lung and lacrimal
-   Can track the lymphocytes subsets. Alternative approach might be 2-3 years of 6 monthly treatment and hope the best.
-   No current role for tracking IgG4 levels


