---
title: " "
output: html_document
---
dont need spikes on bx, subepithelial deposits on the EM will do

## Membranous like glomerulopathy with masked IgG Kappa deposits

-   Light microscopy = classic MN, 25% proliferative changes. Routine Negative IF. But on EM you can see the sub epithelial, and mesangial changes.

-   Paraffin IF – opens up epitopes for ab to bind. Lights up the masked IgGk deposits.
-   Laser capture microdissection suggests serum amyloid P might be an antigenic target
-   Young females, preserved renal function, nephrotic range proteinuria, 55% positive ANA, 2% met SLE criteria
-   Orphan disease - treatment unclear, 44% CKD/ESKD.
-   Can recur in transplant.
-   Probably an autoimmune disease rather than paraprotein disease.

## MISC

Idiopathic membranous can antigen switch (e.g. IgG1 early and IgG4 later in disease)

## NELL 1

-   NELL 1 in primary membranous

-   \~ 5% +

-   10 years older than primary membranous

-   33% had a history of malignancy

-   Folic acid association? 




