---
title: ""
output: 
  html_document:
    includes:
       in_header: GA_Script.html
---

# CKD-MBD & Calcium & Phosphate.

# Calcium

## Physiology - Calcium

-   Freely filtered then about 98% is reabsorbed by the kidney tubules
    -   **Paracellular**: PT 65%, TAL 25%
    -   In TAL, tight junctions express claudin 16/19, which facilitates paracellular calcium reabsorption, and claudin 14, which suppresses it. 
    -   **PTH** inhibits the expression of claudin 14 ( i.e. it inhibits the brakes - thus increases calcium reaborbtion)
    -   **Transcellular**: DCT/CNT 8%
    -   Active transport
    -   **PTH** binds basolaterally, stimulates protein kinase A,C -> increased TRVP5 channels on apical surface -> more calcium leaves the urine and reenteres blood

-   Mostly reabsorbed in proximal tubule alongside sodium and water
    -   This is part of the "bonus sodium" you get from NKCC due to K+ recycling. The K+ that gets pumped back into the tubule via ROMK (see below) leads to a relative +charge in the tubule, thus providing a charge to help drive the paracellular reabsorbtion ofNa/Ca/Mg via the rather leaky paracellular junctions in the PT.
    -   In a high salt diet, there is too much tubular Na so less PT reabsorbtion of the calcium as there is less drive to reabsorb the Na
    -   Which is why you tell calcium stone patients to cut out Salt


    -   Thus urinary calcium rises -> calcium stones!
    
-   ~1-2% (~100-200mg of calcium) is excreted in the urine per day.

## Physiological pearls

-   Hypercalcaemia induces volume contraction in two ways:
    -   nephrogenic DI: Decreased aquaporin expression in Collecting duct, possibly via [increased autophagy](https://pubmed.ncbi.nlm.nih.gov/28139295/)
    -   increased basolateral calcium switches off the ROMK channel in PT, thus shutting down K+ recycling. K+ is the rate limiting step here in NKCC activity (because N and 2Cl get pumped out basolaterally  there is alot less K to begin with in the tubule). This means that NKCC grinds to a halt without the recycled K, and the tubule Na/Cl/H20 increases and is removed, just like a loop diuretic leading to volume depletion.

## PTH

-   If investigating high PTH, sestamibi to check glands for activity.
-   primary hyperPTH commonest cause , 50 per 100,000 patient years

-   Urine calcium is high due to hyperPTH the filtered load will be too high to reabsorb so will overpower PTH's reaborbative action and result in hypercaliuria


## HyperCalcaemia

1.    Check iPTH 

**HIGH or inappropriately normal PTH**

-   24 hour urinary calcium  or urine calcium creatinine ratio high = **Primary hyperPTH**
-   If less than these values, possibly **familial hypocaliuric hypercalcaemia**
    -   family history, asymptomatic
    -   benign condition / inactivating mutation in the calcium-sensing receptor /increased tubular reabsorption of calcium and consequent low urinary calcium excretion.
    -   PTH can be normal or *slightly* elevated
    -   Diagnosis of hypocalciuric Hypercalcaemia - 24 h urine calcium/creatinine clearance ratio < 0.01.
    
**LOW PTH**

Myeloma screen, cancer hunt, Vit D, PTHrp

-   High PTHrp - humoural hypercalcaemia of malignancy
-   High 25(OH)D - Too much vit D
-   High 1,25(OH)D - lymphoma, granulomatous (sarcoid, TB)
-   Normal PTHrp,VITD - Myeloma, Mets, thyrotropin, Vit A

#### Urinary calcium tests

**24 hour urinary collection**

-   HCL bottle
-   Spectrophotometry or atomic absorption spectrophotometry
-   2.5-7.5 mmol/24 h

**Fasting spot urinary calcium:Creatinine ratio**

-   Males: 0.04-0.45 mol/mol creatinine
-   Females: 0.10-0.58 mol/mol creatinine

# Drugs 

## Bisphosphonates

[Nice overview from Touissant et al CJASN](https://cjasn.asnjournals.org/content/4/1/221#sec-2)

Bisphosphonates

-   Non–nitrogen-containing bisphosphonates are clodronate and etidronate
-   Nitrogen-containing bisphosphonates are alendronate, ibandronate, pamidronate, risedronate, and zoledronate are more potent
-   low % intestinal absorption, \<1-5% - lower if not taken as directed
-   When incorporated into bone can hang around in the skeleton for up to 10 years
-   **Renally metabolised**
-   As released from bone can be recycled and taken up again, or renally cleared

**Mechanism**

-   Inhibits FFP synthase - \> less FPP and GGGPP -\> no protein prenylation-\>Kills osteoclasts

**SE**

-   High doses can lead to crystal coating and an associated with osteomalacia
-   Off target effects (via FFP) -osteoblastic cells, monocytes ( where IPP accumulated – bacterial antigen also -\> TNF-a and IGN-y release! – hence flu like symptoms with first bisphosphonate doses). Anergy prevents subsequent symptoms on next exposures.
-   Can bind to gastric cells - \> cell death -\> is this the mechanism of esophagitis/ulceration

**Renal toxicity**

-   High dose pamidronate can cause collapsing FSGS
-   Focal glomerular sclerosis (case series of patients with MM)
-   Pamidronate-induced nephrotic syndrome with renal impairment has also been reported
-   ATN

**Bisphosphonates in CKD**

**TLDR**

-   avoid in low bone turnover, adynamic bone disease, or osteomalacia are present or suspected, as they have potential to do harm.
-   Maybe some use in early CKD as osteoporotic prevention

A [pooled metanalysis of 9 trials, n=8996]( https://pubmed.ncbi.nlm.nih.gov/16294264/) suggests that in CKD 1-3 ( severe disease excluded from all trials) that when secondary causes of low BMD are excluded and blood levels of calcium, phosphate, PTH, ALP, and vitamin D are normal (laboratory features of CKD-MBD), bisphosphonate use in CKD 1 to 3 is safe and results in fracture reduction

CKD 4-5 not been shown to prevent fractures in people with normal BMD or with low baseline markers of bone formation, the subset of patients with severe CKD who might receive therapy would be those with low BMD but high bone resorption.

By reducing calcium, bisphosphonates may stimulate glandular release of PTH and induce parathyroid hyperplasia.

-   Pamidronate probably has best (thin) evidence - in multiple myeloma patients - 10 patients on dialysis
-   Several case series have described pamidronate use in CKD to be safe at doses of 60 to 90 mg administered every 1 to 2 mo
-   Ibandronate 6 HD patients with MM
-   35-50% removed by HD – varies by drug

In chronic use -**1/2 the dose** or reduce the frequency of administration of bisphosphonates in CKD. Limit treatment to 2 years.

Unclear role in patients with steroids – stick to calcium, vitD

Cochrane review post renal transplantation: no individual intervention was associated with a reduction in fracture risk compared with placebo

May result in less atherogensis and vascular calcification but human data is very limited

Case report level effect in calciphylaxis and other calcific diseases


## Cinacalcet

### EVOLVE Trial

*The one that was a bit of a disaster*

[Effect of Cincalcet on CV outcomes in HD](https://www.nejm.org/doi/full/10.1056/nejmoa1205624)

- Patients: HD & secondary hyperparathyroidism (sHPT; intact parathyroid hormone [iPTH] ≥300 pg/ml) 
- Outcome: time until death, myocardial infarction, hospitalization for unstable angina, heart failure, or a peripheral vascular event.
- Results: n= 3883 | HR in Cincalcet vs placebo  0.93; 95% confidence interval, 0.85 to 1.02; P=0.11
- Treatment effects of cinacalcet on fracture rates were similar to effects on CV events in unadjusted ITT analysis

- Not a total wash: Its effective in preventing severe unremitting HPT but thats a bit soft

[Lessons](https://cjasn.asnjournals.org/content/11/3/539)

-   very broad outcomes chosen which mechanistically might not make as much sense ( all cause death, major CV disease)
-   Post hoc evaluation of the treatment effects on CV events using multivariable-adjusted ITT analysis showed relative hazards of 0.88 (95% confidence interval [95% CI], 0.76 to 1.01) for time to first atherosclerotic event, 0.79 (95% CI, 0.66 to 0.96) for heart failure, and 0.79 (95% CI, 0.64 to 0.98) for sudden death; the latter two events are considered outcomes of nonatherosclerotic disease 
-   Heart failure is a sloppy outcome to record - the event adjudication committee only confirmed HF in about 50% of the HF dx made by local investigators
-   parathyroidectomy as an endpoint was used but the referral pathways were not concrete and varied geographically so surrogate of calcium severeity and iPTH levels was used - became a bit murky
-   age difference in groups despite randomisation
-   lower event rate than expected
-   Placebo discontinued for adverse events in 11.8% of patients compared with 15.8% of patients in the cinacalcet group.
-   statistical challenges due to the non adherence and cointerventions


# Parathyroidectomy in CKD

RIE Protocol

## Pre Operative Care
* Alfacalcidol 2mcg bd should be given for 3 days prior to surgery.
* Cinacalcet should be stopped one week before parathyroidectomy.
* Patients at risk of hungry bone syndrome should be identified.

## Hungry Bone Syndrome
Diagnosis hinges on a profound and persistently low calcium level of less than 2.1 mmol/L
for more than four days postoperatively along with hypophosphatemia and normal PTH
levels. Such patients require prolonged, high dose calcium to maintain serum calcium levels.
Often there is also associated hypomagnesemia and hypocalciuria. Risk factors include

* Alkaline phosphatase > 2 times upper limit of normal
* PTH levels> 100 pmol/L
* Radiologic evidence of bone disease
* Higher BMI
* Higher BUN

## Post Operative Care
* Patients should be admitted to ward 215 post operatively and prescribed Alfacalcidol 2mcg bd & Calvive (formally Sandocal1000) 2 tablets tds - Do not take at mealtimes.
* Hold phosphate binders.
* Serum corrected calcium should be measured every 6 hours for the first 24 hours post surgery, and then less frequently if stable.
* Aim for normal serum calcium values (2.2-2.6 mmol/L). Increase calcium supplementation by 50% if calcium falling and half the dose if calcium starts to rise.
* Pay attention to the trend. If the corrected calcium is falling rapidly i.e. >10% over 6 hrs the
development of significant hypocalcaemia is likely and requires more frequent monitoring.
* If calcium <1.8 or if symptomatic, give IV calcium 
* Monitor serum phosphate and magnesium 12 hourly for first 24hrs, then daily.
* Do not treat hypophosphataemia unless serum phosphate falls below 0.35 mmol/l.
* Consider higher calcium dialysate (A232, A231 containing calcium 1.5 mmol) or PD fluid.

## Post Discharge
RRT patients: Monitor serum calcium on each HD session or 3 times a week (for PD
patients) for the first two weeks and weekly checks as required thereafter until stability is
reached.

The dosing of alfacalcidol and calcium supplements post operatively is challenging and both
hypo- and hypercalcaemia are common. Trends in concentration are more important than
absolute values. Consider the following:

* Check adherence and adjust calcium supplement by +- 50%.
* Alfacalcidol dose to increase up to a maximum of 5 micrograms bd but note it takes 3
days to observe effect of increase in dose. Alfacalcidol product specification
recommends increasing dose in increments of 0.25 – 0.5 micrograms but if taking 2
micrograms or more change dose by 1 microgram.
* Check magnesium levels and replace if recurrent /resistant hypocalcaemia

# IV Calcium Infusion
Use calcium gluconate over calcium chloride. Care must be taken to ensure intravenous
calcium is not extravasated. If central line is available this is likely to be most suitable
access. If venous access is not secure, then a central line may be considered.

**Infusion**

* 100ml of 10% calcium gluconate (900mg of elemental calcium) +150 ml of 5% Dextrose
(total volume 250 ml). Final concentration is 3.6mg/ml.
* Start infusion at 0.3ml/kg/hour (1mg/kg/hour. 70kg patient = 21ml/hr)
* Check corrected serum calcium 6 hourly.
* Titrate calcium infusion dose between 0-0.6ml/kg/hour to prevent serum calcium
falling below 1.9mmol/L or rising above 2.4 mmol/L.
* Severe symptoms include paraesthesia, muscle cramps, carpo-pedal spasm, laryngeal
stridor, convulsions, prolonged QT interval, arrhythmias, and hypotension. This will require
bolus IV calcium and subsequent infusion.

### Emergency Calcium Bolus
Emergency situations - Give 10ml of 10% calcium gluconate (2.2mmol calcium) no faster
than 2ml/min (i.e., Over at least 5mins, ECG monitoring recommended); this can be given
peripherally.

##  Common Supplements

Calcium supplements Calcium Content

* Adcal (chewable ) 15 mmol / tablet
* Calcichew(chewable) 12.6 mmol / tablet
* Calvive/ Sandocal 1000 (soluble) 25 mmol / tablet
* Calcichew forte(chewable ) 25 mmol / tablet
(1 mmol = To 40mg Of Elemental Calcium)

# Phosphate


# CKD-MBD

-   High-turnover hyperparathyroid bone disease (osteitis fibrosa), often with abnormal mineralization (mixed uraemic osteodystrophy)
-   Adynamic bone disease – usually inappropriately low PTH (historically aluminium deposition)
-   Association of both conditions with vascular calcification and calciphylaxis
-   Many CKD patients have lower bone mass and osteoporotic BMD ( 2.5 SD below young Caucasian female)
-   Osteoporosis & metabolic acidosis, low vit D, low activation of vit D, renal osteodystrophy.
-   BMD – harder to read in CKD – calcified soft tissues,
-   Higher rates of \#
-   Quantitative double tetracycline-labelled bone histomorphometry is gold standard alongside a bone biopsy.
-   Biopsy is pretty pointless imo unless incredible need to give a bisphosphonate

