---
title: ""
output:
  html_document:
    includes:
      in_header: GA_Script.html
---

# Tumour Lysis syndrome

-   Can be spontaneous or treatment related
-   Massive released of intracellular nucleic acids, phophshate, k+
-   Often has a drop in calcium as phos-binds to it
-   Malignant cells have 4x the phosphate of non-malignant counterparts
-   Hyperphos is less common in the spontaneous tumour lysis setting as the growing cells can take up released phosphate so end up establishing an equilibrium
-   Can have high K – consider pseudokyperk in leukaemia/highly cellular disease
-   Can manifest with AKI, cardiac arrhythmia, or seizure.

**Classic tumours: Fast growing, highly cellular**

-   non-Hodgkin’s lymphoma (NHL)
-   acute lymphoblastic leukemia (ALL)
-   chronic lymphocytic leukemia (CLL)
-   germ cell tumors

## AKI

#### Crystal injury

-   Uric Acid is high -> Intracellular purine nucleic acids are catabolized to xanthine and hypoxanthine, which get converted to uric acid by the enzyme xanthine oxidase.
-   Uric acid is poorly soluble in water, precipitates in an acidic environment (like distal tubules and collecting ducts).
-   Calcium-phosphate crystals can also precipitate out into tubules.
-   **Epitaxy:** Uric acid crystals and calcium phosphate crystals form a seed layer for each other. Calcium phosphate coats the otherwise soluble uric acid. Thus, the pathological crystals are mixed.
-   AKI - \> higher concentrations -\> more crystallisation -\>vicious cycle

#### Non crystal injury

-   Uric acid is also vasoconstrictive and impairs autoregulation
-   Histones are cytotoxic and cause endothelial injury.
-   Cytokines also released.

## Treatment

Prophylactic hydration and rasburicase is best option

-   Very careful and frequent labs. HDU/ITU possibly.
-   Treat K+ medically if possible, RRT on the table
-   volume resuscitate with N.Saline
    -   2 ml/kg/hour or atleast [3 litres](https://www.karger.com/Article/FullText/509934) per day
    -   Avoid calcium containing fluids
-   Non calcium binder may have a role, like sevelamer
-   Caution replacing calcium as may worsening Ca-Phos precipitation, let it ride low as feasible but treat if symptomatic

### Rasburicase

-   recombinant urate oxidase
-   breaks down uric acid into allantoin, which is water-soluble and non-nephrotoxic
-   contraindicated in G6PD def
-   in patients with G6PD deficiency, uric acid metabolism leads to hydrogen peroxide generation leading to methemoglobinemia and, in severe cases, Hemolysis 
-   Haemolysis usually occurs 2 to 3 days after starting rasburicase
-   Monitor closely if no pre chemo genetic testing was done – especially Mediterranean/African ancestry
-   Note that the post-rasburicase uric acid level for monitoring needs to be processed urgently (ideally in a lithium heparin tube, and on ice) to stop the rasburicase from continuing to reduce uric acid in vitro

**QHMAC**

-   3mg (i.e. 2 x 1.5mg vials) as a single dose. This dose should bring uric acid into the normal range but can be repeated if necessary. Patients should be monitored and may require a repeat dose every 2-3 days if serum urate returns to greater than norm

### Allopurinol

-   Not recommended as xanthine in the urine and serum can be elevated after the administration of allopurinol because of the inhibition of the conversion of xanthine to uric acid.
-   Xanthine by itself has limited solubility and can crystallize in the renal tubules making the obstructive uropathy associated with tumor lysis syndrome worse
-   potential drug-to-drug interaction with azathioprine

### Other



No to **alkanisation** of urine

**Diuretics** for overload if required

### RRT

-   severe AKI with life-threatening hyperkalemia, hyperphosphatemia, and hyperuricemia
-   CVVH etc may be safer
